// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmlgqzzhbiisgmysaoww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtbGdxenpoYmlpc2dteXNhb3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzgxMjAsImV4cCI6MjA1NzU1NDEyMH0.vWGssonsYSw0NDR9MMVd_isXWt5u2hQNsXqHRiK7lDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);